### ISSUE TITLE
Это хак ))

### ISSUE THREAD

**Issue by coursar** [Ronin52/sqliteconnector#5]
https://github.com/Ronin52/sqliteconnector/blob/6e42e33d7a4281dcc3fe6dbf07c7ff9ad6741e92/src/main/java/ru/rosbank/javaschool/sqliteconnector/kotlin/beans.kt#L18-L25

Kotlin BeanDefnitionDSL пока не даёт возможности достучаться до BeanDefinition простым способом. Поэтому тут стоило сделать вот так:

```java
public class KotlinSQLiteDataSource extends SQLiteDataSource {
  private final SQLiteDataSource dataSource = new SQLiteDataSource();

  public KotlinSQLiteDataSource(@Value("${db_url}") String url) {
    dataSource.setUrl(url);
  }
}
```

**Comment by Ronin52** [comment]
Тоесть так нельзя?) Но оно же работает)

**Comment by coursar** [comment]
Нет, ну вы напрямую читаете из property-файла, BFPP тут не причём вообще

**Comment by Ronin52** [comment]
но я же читаю в определении бина, чтобы получить данные. Аааа, понял я в чем прикол, я котлином скажем так подставляю, а не бином Parseholder

**Comment by coursar** [comment]
Вернее вот так:
```java
public class KotlinSQLiteDataSource extends SQLiteDataSource {
  public KotlinSQLiteDataSource(@Value("${db_url}") String url) {
    setUrl(url);
  }
}
```
